robot:

  # Arm Trajectory Controllers ---------------------------------------
  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    constraints:
      goal_time: 1.6
      stopped_velocity_tolerance: 0.05
      joint_1: {trajectory: 0.8, goal: 0.9}
      joint_2: {trajectory: 0.8, goal: 0.9}
      joint_3: {trajectory: 0.8, goal: 0.9}
      joint_4: {trajectory: 0.8, goal: 0.9}
      joint_5: {trajectory: 0.8, goal: 0.9}
      joint_6: {trajectory: 0.8, goal: 0.9}
    stop_trajectory_duration: 0.5
    state_publish_rate: 25
    action_monitor_rate: 10
  # Gripper Trajectory Controllers ---------------------------------------
  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - left_jaw_joint
      - right_jaw_joint

