controller_list:
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - left_jaw_joint
      - right_jaw_joint
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
initial:  # Define initial robot poses per group
  - group: hand
    pose: open
  - group: arm
    pose: home